### ISSUE TITLE
Wrong version in package.json

### ISSUE THREAD

**Issue by pilare** [igvteam/igv-utils#12]
We are using igv and recently we started having issues during building packages, as there is a conflict before version 1.2.7 and 1.2.6. The recent `igv-utils` is still marked as 1.2.6 in package.json instead 1.2.7. Because of that the `yarn` or `npm` are having issues to update to newest version.

```
{  "name": "igv-utils",  "version": "1.2.6",  "description": "Misc code shared by igvteam projects",  "module": "src/index.js",  "files": [    "src/**"  ],
```

**Comment by jrobinso** [comment]
OK that was a mistake.  I will probably have to tag a new release (1.2.8) to fix it.  In what context are you seeing this error, are you using igv-utils independently, or trying to build one of dependent projects (igv.js or igv-webapp)?

**Comment by pilare** [comment]
I'm using `igv.js` in our react application. Locally I'm getting only warnings during `yarn install`. 

```
warning Pattern ["igv-utils@github:igvteam/igv-utils#v1.2.7"] is trying to unpack in the same destination "/Users/pilare/Library/Caches/Yarn/v6/npm-igv-utils-1.2.6-9d9fc2b26074417b943999592b484ce2ea2b9284/node_modules/igv-utils" as pattern ["igv-utils@git+https://github.com/igvteam/igv-utils.git#v1.2.7"]. This could result in non-deterministic behavior, skipping.
```
But in Jenkins pipeline I'm getting an error:

```
error Couldn't find the binary git
```
I was able to fix it by adding git to the docker image. Seems that after we ejected our react app, the container didn't have ability to build it from git source anymore.

So those version numbers are not crucial for as anymore. @jrobinso, thank you for a fast response, and great project.

**Comment by jrobinso** [comment]
I straightened out the numbers, but I don't understand what yarn and react are doing, they must have some heuristics with expectations of some correspondence between git tags and package.json version numbers.

Our documented build process does not use yarn, it uses NPM and rollup,  and has not failed (its gets built on every commit).  In any event we will try to keep version numbers and tags in sync.
